name : GitHub actions workflow example
on : [push]
jobs:
  Discover-GitHub-Actions-Workflows :
    runs-on : ubuntu-latest
    steps :
     - run : echo "${{github.event.name}} event automatically triggered this job"
     - run : echo "A ${{runner.os}} has this hosted on GitHub"
     - run : echo "$${{github.repository}} is updated. Updated branch is $${{github.ref}}"
     - uses : actions/checkout@v3
     - run : echo "The runner has cloned the ${{github.repository}} repository"
     - uses : actions/checkout@v3
     - run : echo "The runner has closed the ${{github.repository}} repository"
     - run : ls -l ${{github.workspace}}
     - run : echo "Push status = ${{job.status}}"
